### ISSUE TITLE
Q&A: Is it possible to build gpgme with MUSL

### ISSUE THREAD

**Issue by Byron** [johnschug/rust-gpgme#12]
For [`share-secrets-safely`](https://github.com/Byron/share-secrets-safely) I have been hitting my head against a brick wall so far on my quest to get a fully static build on OSX, as well as one that allows to use MUSL. Whenever a wall breaks down, there is another one behind it, making the endeavor very cumbersome and unrewarding.

_Thus I am reaching out to you just to ask_: **Do you think it's feasible and possible to get a fully static and MUSL build with GPGME?**

Thanks so much for sharing your expertise :)!

**Comment by johnschug** [comment]
It should be possible using the next branch.

**Comment by Byron** [comment]
Thanks a lot! 
I already had a look at it, and believe it would be best to wait until it is published.
In the meantime, I will just link dynamically, which seems to work consistently, or statically without musl.

I am really thankful for the work you put into this library and hope to be contributing when I find something suitable:)!
